//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModelContext : DbContext
    {
        public DataModelContext()
            : base("name=DataModelContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HR_Base> HR_Base { get; set; }
        public virtual DbSet<HR_Department> HR_Department { get; set; }
        public virtual DbSet<HR_Error> HR_Error { get; set; }
        public virtual DbSet<HR_Level> HR_Level { get; set; }
        public virtual DbSet<HR_Org> HR_Org { get; set; }
        public virtual DbSet<HR_Relation> HR_Relation { get; set; }
        public virtual DbSet<HR_User> HR_User { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<T_Case> T_Case { get; set; }
        public virtual DbSet<t_Case_Clients> t_Case_Clients { get; set; }
        public virtual DbSet<T_Case_CommissionDateLog> T_Case_CommissionDateLog { get; set; }
        public virtual DbSet<t_Case_Main> t_Case_Main { get; set; }
        public virtual DbSet<t_Case_Property> t_Case_Property { get; set; }
        public virtual DbSet<T_Case_StartRemit> T_Case_StartRemit { get; set; }
        public virtual DbSet<T_DDL_ItemList> T_DDL_ItemList { get; set; }
        public virtual DbSet<T_DelayCommForGsl> T_DelayCommForGsl { get; set; }
        public virtual DbSet<T_DirectorManagerAccount> T_DirectorManagerAccount { get; set; }
        public virtual DbSet<t_EditNum_Log> t_EditNum_Log { get; set; }
        public virtual DbSet<T_Entrust> T_Entrust { get; set; }
        public virtual DbSet<T_EntrustAccount> T_EntrustAccount { get; set; }
        public virtual DbSet<T_EntrustFlow> T_EntrustFlow { get; set; }
        public virtual DbSet<T_EntrustGartherPay> T_EntrustGartherPay { get; set; }
        public virtual DbSet<T_EntrustHoldComm> T_EntrustHoldComm { get; set; }
        public virtual DbSet<T_EntrustResult> T_EntrustResult { get; set; }
        public virtual DbSet<t_Flow_Base> t_Flow_Base { get; set; }
        public virtual DbSet<t_Flow_CaseOver> t_Flow_CaseOver { get; set; }
        public virtual DbSet<T_Flow_CaseUnion> T_Flow_CaseUnion { get; set; }
        public virtual DbSet<T_Flow_CaseUnionDetail> T_Flow_CaseUnionDetail { get; set; }
        public virtual DbSet<t_Flow_Clients> t_Flow_Clients { get; set; }
        public virtual DbSet<t_Flow_ClinetInfo_Log> t_Flow_ClinetInfo_Log { get; set; }
        public virtual DbSet<t_Flow_Commision> t_Flow_Commision { get; set; }
        public virtual DbSet<T_Flow_CommissionRemit> T_Flow_CommissionRemit { get; set; }
        public virtual DbSet<T_Flow_DelayCommission> T_Flow_DelayCommission { get; set; }
        public virtual DbSet<t_Flow_Distribution> t_Flow_Distribution { get; set; }
        public virtual DbSet<t_Flow_DistributionDetail> t_Flow_DistributionDetail { get; set; }
        public virtual DbSet<T_Flow_DistributionDetailbak> T_Flow_DistributionDetailbak { get; set; }
        public virtual DbSet<t_Flow_GatherPay> t_Flow_GatherPay { get; set; }
        public virtual DbSet<T_Flow_Litigation> T_Flow_Litigation { get; set; }
        public virtual DbSet<T_Flow_Litigation_QSList> T_Flow_Litigation_QSList { get; set; }
        public virtual DbSet<t_Flow_Loan> t_Flow_Loan { get; set; }
        public virtual DbSet<t_Flow_LoanChange> t_Flow_LoanChange { get; set; }
        public virtual DbSet<t_Flow_Mortgage> t_Flow_Mortgage { get; set; }
        public virtual DbSet<T_Flow_NonIncomeDetail> T_Flow_NonIncomeDetail { get; set; }
        public virtual DbSet<t_Flow_Trade> t_Flow_Trade { get; set; }
        public virtual DbSet<t_innerfinance_case> t_innerfinance_case { get; set; }
        public virtual DbSet<t_innerfinance_flow> t_innerfinance_flow { get; set; }
        public virtual DbSet<T_Log_CommissionFollow> T_Log_CommissionFollow { get; set; }
        public virtual DbSet<t_Log_EditClient> t_Log_EditClient { get; set; }
        public virtual DbSet<T_Log_News> T_Log_News { get; set; }
        public virtual DbSet<T_Log_PrintCash> T_Log_PrintCash { get; set; }
        public virtual DbSet<T_PrintCash_Bank> T_PrintCash_Bank { get; set; }
        public virtual DbSet<T_Pro_Project> T_Pro_Project { get; set; }
        public virtual DbSet<T_Pro_ProjectCashRule> T_Pro_ProjectCashRule { get; set; }
        public virtual DbSet<t_Pro_ProjectDaili> t_Pro_ProjectDaili { get; set; }
        public virtual DbSet<T_Pro_ProjectUser> T_Pro_ProjectUser { get; set; }
        public virtual DbSet<t_pub_user_parents> t_pub_user_parents { get; set; }
        public virtual DbSet<T_pub_UserParents> T_pub_UserParents { get; set; }
        public virtual DbSet<T_Publish_NewsLog> T_Publish_NewsLog { get; set; }
        public virtual DbSet<t_Receipt_Detail> t_Receipt_Detail { get; set; }
        public virtual DbSet<t_Receipt_Log> t_Receipt_Log { get; set; }
        public virtual DbSet<t_Receipt_Manage> t_Receipt_Manage { get; set; }
        public virtual DbSet<t_Receipt_Yellow> t_Receipt_Yellow { get; set; }
        public virtual DbSet<hr_org_bak> hr_org_bak { get; set; }
        public virtual DbSet<hr_OrgDepartment> hr_OrgDepartment { get; set; }
        public virtual DbSet<hr_userOrg> hr_userOrg { get; set; }
        public virtual DbSet<ORG_Unit> ORG_Unit { get; set; }
        public virtual DbSet<ORG_Unit_20120229> ORG_Unit_20120229 { get; set; }
        public virtual DbSet<ORG_Unit_bak> ORG_Unit_bak { get; set; }
        public virtual DbSet<PropertyCopy> PropertyCopy { get; set; }
        public virtual DbSet<SYSConfig> SYSConfig { get; set; }
        public virtual DbSet<T_CaseClient> T_CaseClient { get; set; }
        public virtual DbSet<T_EntrustFlowBK> T_EntrustFlowBK { get; set; }
        public virtual DbSet<T_EntrustSpecialUser> T_EntrustSpecialUser { get; set; }
        public virtual DbSet<T_EntrustUser> T_EntrustUser { get; set; }
        public virtual DbSet<t_Flow_DistributionCMS> t_Flow_DistributionCMS { get; set; }
        public virtual DbSet<TWF_TCB_Property> TWF_TCB_Property { get; set; }
    }
}
