//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_OrgDepartment
    {
        public System.Guid ID { get; set; }
        public string DeptCode { get; set; }
        public string DeptName { get; set; }
        public string Addr { get; set; }
        public string Lv5Name { get; set; }
        public string Lv5Code { get; set; }
        public string Lv5Position { get; set; }
        public string Lv6Name { get; set; }
        public string Lv6Code { get; set; }
        public string Lv6Position { get; set; }
        public string Lv7Name { get; set; }
        public string Lv7Code { get; set; }
        public string Lv7Position { get; set; }
        public string Lv8Name { get; set; }
        public string Lv8Code { get; set; }
        public string Lv8Position { get; set; }
        public string Lv9Name { get; set; }
        public string Lv9Code { get; set; }
        public string Lv9Position { get; set; }
        public string Lv10Name { get; set; }
        public string Lv10Code { get; set; }
        public string Lv10Position { get; set; }
        public Nullable<int> isNew { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> Endtime { get; set; }
        public Nullable<int> isLeave { get; set; }
        public string ischange { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public System.DateTime drecordtime { get; set; }
    }
}
