//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Relation
    {
        public int relatId { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> LatestFlag { get; set; }
        public Nullable<int> baseId { get; set; }
        public Nullable<int> deptId { get; set; }
    
        public virtual HR_Base HR_Base { get; set; }
        public virtual HR_Department HR_Department { get; set; }
    }
}
