//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_User
    {
        public int id { get; set; }
        public string User_Name { get; set; }
        public string User_Id { get; set; }
        public string User_Code { get; set; }
        public string Agency_UserId { get; set; }
    }
}
