//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_userOrg
    {
        public System.Guid ID { get; set; }
        public string userCode { get; set; }
        public string UserName { get; set; }
        public string Job { get; set; }
        public string duty { get; set; }
        public string level { get; set; }
        public string orgName { get; set; }
        public string OrgCode { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string userSel { get; set; }
        public Nullable<int> isLeave { get; set; }
        public Nullable<int> IsNew { get; set; }
        public string InFlag { get; set; }
        public string ChangeFlag { get; set; }
        public string Area { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> month { get; set; }
        public string userSel2 { get; set; }
        public System.DateTime dRecordTime { get; set; }
    }
}
