//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORG_Unit_bak
    {
        public Nullable<System.Guid> ID { get; set; }
        public System.Guid FrameworkID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<byte> CategoryID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<byte> StatusID { get; set; }
        public string OrderCode { get; set; }
        public string SelfCode { get; set; }
        public Nullable<System.Guid> UnitLevel { get; set; }
        public string FullName { get; set; }
        public string K3UnitCode { get; set; }
    }
}
