//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyCopy
    {
        public string PropertyID { get; set; }
        public string CityName { get; set; }
        public string DistrictName { get; set; }
        public string EstateID { get; set; }
        public string RoomNo { get; set; }
        public Nullable<int> Floor { get; set; }
        public string Trade { get; set; }
        public string Status { get; set; }
        public string CountF { get; set; }
        public string CountT { get; set; }
        public string CountW { get; set; }
        public string CountY { get; set; }
        public Nullable<bool> FlagRecommand { get; set; }
        public string PropertyUsage { get; set; }
        public string PropertyType { get; set; }
        public string PropertyDirection { get; set; }
        public string PropertyLook { get; set; }
        public string PropertyBuy { get; set; }
        public string PropertyCommission { get; set; }
        public string PropertySource { get; set; }
        public Nullable<double> Square { get; set; }
        public Nullable<decimal> PriceUnit { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> PriceBase { get; set; }
        public Nullable<decimal> RentPriceUnit { get; set; }
        public Nullable<decimal> RentPrice { get; set; }
        public Nullable<decimal> MgtPrice { get; set; }
        public System.DateTime TrustDate { get; set; }
        public string DeptID { get; set; }
        public string EmpID { get; set; }
        public string PropertyDecoration { get; set; }
        public string PropertyFloor { get; set; }
        public string Remark { get; set; }
        public string RegPerson { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public string ModPerson { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<bool> FlagPrivate { get; set; }
        public string PropertyTrust { get; set; }
        public string KeyNo { get; set; }
        public string CompleteYear { get; set; }
        public string CompleteMonth { get; set; }
        public string PropertyOccupy { get; set; }
        public string PropertyOwn { get; set; }
        public Nullable<double> SquareUse { get; set; }
        public Nullable<System.DateTime> LastFollowDate { get; set; }
        public Nullable<bool> FlagTrashed { get; set; }
        public Nullable<bool> FlagDeleted { get; set; }
        public string OwnerName { get; set; }
        public string OwnerTel { get; set; }
        public string ContactName { get; set; }
        public string PropertyFurniture { get; set; }
        public Nullable<bool> FlagSpecial { get; set; }
        public string PropertyNo { get; set; }
        public Nullable<double> PriceLine { get; set; }
        public Nullable<double> RentPriceLine { get; set; }
        public string Address { get; set; }
        public string PropertyCertificate { get; set; }
        public string PropertyElectric { get; set; }
        public Nullable<System.DateTime> ExDate { get; set; }
        public Nullable<int> FloorAll { get; set; }
        public Nullable<System.DateTime> HandOverDate { get; set; }
        public string UnitName { get; set; }
        public string RentUnitName { get; set; }
        public Nullable<int> PhotoCount { get; set; }
        public string CustomField1 { get; set; }
        public string CustomField2 { get; set; }
        public bool IsTran { get; set; }
        public string TrustNo { get; set; }
        public Nullable<System.DateTime> TrustExpired { get; set; }
        public string TrustRemark { get; set; }
        public string TrustDeptID { get; set; }
        public string TrustEmpID { get; set; }
        public Nullable<System.DateTime> RecommandExpired { get; set; }
        public string OwnerJob { get; set; }
        public string OwnerSex { get; set; }
        public string OwnerAge { get; set; }
        public string OwnerIncome { get; set; }
        public string CentaDBID { get; set; }
        public Nullable<double> CustNumeric1 { get; set; }
        public Nullable<double> CustNumeric2 { get; set; }
        public Nullable<double> CustNumeric3 { get; set; }
        public Nullable<System.DateTime> CustDate1 { get; set; }
        public Nullable<System.DateTime> CustDate2 { get; set; }
        public Nullable<System.DateTime> CustDate3 { get; set; }
        public string CustString1 { get; set; }
        public string CustString2 { get; set; }
        public string CustString3 { get; set; }
        public string PropertyCardNo { get; set; }
        public string PropertyMan { get; set; }
        public Nullable<System.DateTime> PropertyCardDate { get; set; }
        public int FlagFiveYears { get; set; }
        public string EmpIDRecommandAreaManager { get; set; }
        public string PropertyCardAddress { get; set; }
        public string PropertyCardOther { get; set; }
        public string PropertyCardType { get; set; }
        public string PropertyLevel { get; set; }
        public int FlagLookTogether { get; set; }
        public string LookTogetherEmpID { get; set; }
        public decimal GuidePrice { get; set; }
        public decimal TaxPersonal { get; set; }
        public decimal TaxBusiness { get; set; }
        public decimal TaxLand { get; set; }
        public decimal TaxStampDuty { get; set; }
        public decimal TaxDeed { get; set; }
        public decimal LandTransfer { get; set; }
        public decimal TaxOther { get; set; }
        public string CommissionAlloc { get; set; }
        public string RoomTypeID { get; set; }
        public int FlagRoomList { get; set; }
        public bool FlagSecond { get; set; }
        public bool FlagMortgage { get; set; }
        public bool FlagLimited { get; set; }
        public Nullable<System.DateTime> ExpiredDateLimited { get; set; }
        public string LimitedEmpID { get; set; }
        public int FlagCarPark { get; set; }
        public string CarPos { get; set; }
    }
}
