//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSConfig
    {
        public long ID { get; set; }
        public string OrgRole { get; set; }
        public string OrgName { get; set; }
        public string FlowType { get; set; }
        public Nullable<int> AttachmentUpLoad { get; set; }
        public Nullable<int> AttachmentBrower { get; set; }
        public Nullable<int> AttachmentList { get; set; }
        public Nullable<int> ZPriceView { get; set; }
    }
}
