//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Case_Clients
    {
        public string GUID { get; set; }
        public string RootId { get; set; }
        public string ClientType { get; set; }
        public string ClientName { get; set; }
        public string Serial { get; set; }
        public string PhoneCountry { get; set; }
        public string PhoneCity { get; set; }
        public string Phone { get; set; }
        public string MobilePhone1 { get; set; }
        public string MobilePhone2 { get; set; }
        public string FaxCountry { get; set; }
        public string FaxCity { get; set; }
        public string Fax { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Address { get; set; }
        public string AddrCode { get; set; }
        public string Attribute { get; set; }
        public string AttrRegion { get; set; }
        public string AttrDetail { get; set; }
        public string PaperType { get; set; }
        public string Paper { get; set; }
        public string HaveProperty { get; set; }
        public string Intent { get; set; }
        public string YearInSH { get; set; }
        public string DealInCenta { get; set; }
        public string Source { get; set; }
        public string Media { get; set; }
        public string BankType { get; set; }
        public string Bank { get; set; }
        public Nullable<System.DateTime> recording_time { get; set; }
        public Nullable<System.DateTime> updated_time { get; set; }
        public string CustomerID { get; set; }
        public string TurnOverTime { get; set; }
        public string cust_position { get; set; }
        public string AttrDetailOther { get; set; }
    }
}
