//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Case
    {
        public int Id { get; set; }
        public string RootID { get; set; }
        public string ctm_code { get; set; }
        public string agent_username { get; set; }
        public string agent_realname { get; set; }
        public string agent_mobile { get; set; }
        public string grp_code { get; set; }
        public string grp_name { get; set; }
        public string grp_mgr_username { get; set; }
        public string grp_mgr_realname { get; set; }
        public string grp_mgr_mobile { get; set; }
        public string ar_code { get; set; }
        public string ar_name { get; set; }
        public string ar_mgr_username { get; set; }
        public string ar_mgr_realname { get; set; }
        public string ar_mgr_mobile { get; set; }
        public string wz_direct_username { get; set; }
        public string wz_direct_realname { get; set; }
        public string property_address { get; set; }
        public string property_id { get; set; }
        public string del_code { get; set; }
        public string consult_username { get; set; }
        public string consult_realname { get; set; }
        public System.DateTime create_time { get; set; }
        public System.DateTime update_time { get; set; }
        public string partner { get; set; }
    }
}
