//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Case_Property
    {
        public string RootId { get; set; }
        public string PropertyName { get; set; }
        public string FullAddress { get; set; }
        public string Serial { get; set; }
        public string Block { get; set; }
        public string Road { get; set; }
        public string Lane { get; set; }
        public string Number { get; set; }
        public string Room { get; set; }
        public string PropertyType { get; set; }
        public Nullable<decimal> Square { get; set; }
        public string SquareType { get; set; }
        public Nullable<decimal> House { get; set; }
        public Nullable<decimal> Hall { get; set; }
        public Nullable<decimal> Toilet { get; set; }
        public Nullable<decimal> HouseKeeper { get; set; }
        public Nullable<decimal> SouthHouse { get; set; }
        public Nullable<decimal> SouthHall { get; set; }
        public Nullable<decimal> ViewHall { get; set; }
        public Nullable<decimal> HouseLevel { get; set; }
        public Nullable<decimal> Step { get; set; }
        public Nullable<decimal> Home { get; set; }
        public string Model { get; set; }
        public Nullable<decimal> HouseAge { get; set; }
        public string Fitment { get; set; }
        public string Furniture { get; set; }
        public Nullable<decimal> FitmentYear { get; set; }
        public string QuietLevel { get; set; }
        public string Car { get; set; }
        public Nullable<System.DateTime> updated_time { get; set; }
        public string PropertyId { get; set; }
        public string Area { get; set; }
        public string DistrictName { get; set; }
        public string EstateID { get; set; }
        public string Spell { get; set; }
        public string Address { get; set; }
        public string AgencyPropertyName { get; set; }
        public string SourceFlag { get; set; }
        public string AgencyID { get; set; }
        public string Delegation_Code { get; set; }
        public string propertyTypeOther { get; set; }
        public Nullable<int> Kitchen { get; set; }
        public string CQAddress { get; set; }
        public string EstateSortOth { get; set; }
    
        public virtual t_Case_Main t_Case_Main { get; set; }
    }
}
