//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Case_CommissionDateLog
    {
        public long LogID { get; set; }
        public string RootID { get; set; }
        public System.DateTime OldCommissionDate { get; set; }
        public System.DateTime NewCommissionDate { get; set; }
        public string ModifyUserID { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
