//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DirectorManagerAccount
    {
        public long ID { get; set; }
        public string ManagerUser { get; set; }
        public string ManagerUserCode { get; set; }
        public string ManagerUserID { get; set; }
        public string ManagerSecretaryUser { get; set; }
        public string ManagerSecretaryUserCode { get; set; }
        public string ManagerSecretaryUserID { get; set; }
        public string ParentID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime dRecordTime { get; set; }
        public string ParentUserName { get; set; }
        public string ParentUserCode { get; set; }
    }
}
