//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EntrustAccount
    {
        public long ID { get; set; }
        public string AccUser { get; set; }
        public string AccUserCode { get; set; }
        public string AccUserID { get; set; }
        public string Account { get; set; }
        public Nullable<decimal> AmountMax { get; set; }
        public Nullable<decimal> AmountAvailable { get; set; }
        public Nullable<decimal> AmountLimit { get; set; }
        public string ParentID { get; set; }
        public Nullable<int> IsWast { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
        public System.DateTime dRecordTime { get; set; }
    }
}
