//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EntrustHoldComm
    {
        public long ID { get; set; }
        public string Prootid { get; set; }
        public string wfmid { get; set; }
        public string User { get; set; }
        public string UserCode { get; set; }
        public string UserID { get; set; }
        public Nullable<decimal> HoldComm { get; set; }
        public Nullable<decimal> HoldCommed { get; set; }
        public Nullable<decimal> NextHoldComm { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public System.DateTime dRecordTime { get; set; }
    }
}
