//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EntrustGartherPay
    {
        public long ID { get; set; }
        public string Prootid { get; set; }
        public string wfmid { get; set; }
        public string FlowName { get; set; }
        public Nullable<long> FlowID { get; set; }
        public string PayType { get; set; }
        public string PayNum { get; set; }
        public Nullable<decimal> PayAmount { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
        public string UserType { get; set; }
        public string PayUser { get; set; }
        public string PayUserCode { get; set; }
        public string PayUserID { get; set; }
        public string UserRole { get; set; }
        public string OrgName { get; set; }
        public Nullable<long> OrgId { get; set; }
        public string AccUserID { get; set; }
        public string PayReason { get; set; }
        public Nullable<long> IsWast { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
        public Nullable<System.DateTime> dRecordTime { get; set; }
    }
}
