//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EntrustSpecialUser
    {
        public long ID { get; set; }
        public string UserName { get; set; }
        public string UserCode { get; set; }
        public string UserID { get; set; }
        public string Bank { get; set; }
        public string CardNo { get; set; }
        public string UserType { get; set; }
        public long IsWaster { get; set; }
        public string CardAccount { get; set; }
    }
}
