//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EntrustFlow
    {
        public long ID { get; set; }
        public string Prootid { get; set; }
        public string wfmid { get; set; }
        public string FlowName { get; set; }
        public Nullable<long> FlowID { get; set; }
        public string TradeType { get; set; }
        public Nullable<int> IsSign { get; set; }
        public Nullable<System.DateTime> EntrustStart { get; set; }
        public Nullable<System.DateTime> EntrustEnd { get; set; }
        public Nullable<decimal> Price1 { get; set; }
        public Nullable<decimal> Price2 { get; set; }
        public Nullable<decimal> CommAmount { get; set; }
        public Nullable<decimal> CommRate { get; set; }
        public Nullable<System.DateTime> EntrustDate { get; set; }
        public string EntrustType { get; set; }
        public Nullable<int> IsPayOwn { get; set; }
        public string UserName { get; set; }
        public string UserID { get; set; }
        public string UserCode { get; set; }
        public string OrgName { get; set; }
        public Nullable<long> OrgID { get; set; }
        public string ApplyUser { get; set; }
        public string ApplyID { get; set; }
        public string ApplyCode { get; set; }
        public string QDIdeaType { get; set; }
        public string QDIdea { get; set; }
        public string QDArea { get; set; }
        public string QDid { get; set; }
        public string QDName { get; set; }
        public string QDCode { get; set; }
        public Nullable<System.DateTime> payTime { get; set; }
        public Nullable<decimal> payAmount { get; set; }
        public string payFor { get; set; }
        public string payRemark { get; set; }
        public string ReasonGR { get; set; }
        public string ReasonGS { get; set; }
        public Nullable<int> IsNoInterAgency { get; set; }
        public string CurState { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
        public Nullable<int> IsNew { get; set; }
        public Nullable<int> IsWast { get; set; }
        public Nullable<System.DateTime> dRecordTime { get; set; }
        public string CQUser { get; set; }
        public string QSUser { get; set; }
        public string QSContact { get; set; }
        public string Prox { get; set; }
        public string ProxContact { get; set; }
        public string Remark { get; set; }
        public string PayerReceiver { get; set; }
        public string PayerReceiverID { get; set; }
        public string PayerReceiverCode { get; set; }
        public string Bank { get; set; }
        public string CardNo { get; set; }
        public string AreaDirectorName { get; set; }
        public string AreaDirectorID { get; set; }
        public string AreaDirectorCode { get; set; }
        public string DelegationAgreementID { get; set; }
    }
}
