//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Entrust
    {
        public long ID { get; set; }
        public string Prootid { get; set; }
        public string EntrustID { get; set; }
        public string Crootid { get; set; }
        public string CompanyNum { get; set; }
        public string FullAddress { get; set; }
        public string PropertyID { get; set; }
        public Nullable<decimal> Square { get; set; }
        public Nullable<decimal> Floor { get; set; }
        public string TradeTypePro { get; set; }
        public string EstateName { get; set; }
        public string EstateID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public System.DateTime dRecordTime { get; set; }
        public Nullable<int> isclear { get; set; }
        public Nullable<int> isLock { get; set; }
        public string LockReason { get; set; }
        public Nullable<System.DateTime> ClearTime { get; set; }
    }
}
