//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EntrustResult
    {
        public long ID { get; set; }
        public string Prootid { get; set; }
        public string Wfmid { get; set; }
        public string FlowName { get; set; }
        public Nullable<long> FlowID { get; set; }
        public string Result { get; set; }
        public string EntrustLog { get; set; }
        public string Crootid { get; set; }
        public string CFlowName { get; set; }
        public string Cwfmid { get; set; }
        public Nullable<int> IsOver { get; set; }
        public Nullable<System.DateTime> OverTime { get; set; }
        public Nullable<int> IsNew { get; set; }
        public Nullable<int> IsWast { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
        public Nullable<System.DateTime> dRecordTime { get; set; }
        public Nullable<System.DateTime> HSTime { get; set; }
        public Nullable<decimal> HSAmount { get; set; }
        public Nullable<decimal> ResultAmount { get; set; }
    }
}
