//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Flow_DistributionDetailbak
    {
        public long Id { get; set; }
        public string RootId { get; set; }
        public string WfmId { get; set; }
        public string UserName { get; set; }
        public string UserCode { get; set; }
        public string UserId { get; set; }
        public string PercentType { get; set; }
        public string NewAgencyRole { get; set; }
        public Nullable<decimal> BasePercent { get; set; }
        public Nullable<decimal> RealPercent { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> dRecordTime { get; set; }
    }
}
