//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Flow_Commision
    {
        public string RootId { get; set; }
        public string WfmId { get; set; }
        public string ReceiptNum { get; set; }
        public Nullable<System.DateTime> GPDate { get; set; }
        public string Proposer { get; set; }
        public string ProposerId { get; set; }
        public string Usage { get; set; }
        public string PrintAddress { get; set; }
        public Nullable<System.DateTime> PrintTime { get; set; }
        public string MoneyType { get; set; }
        public Nullable<decimal> MoneyAmount { get; set; }
        public Nullable<decimal> SourceMoneyAmount { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<decimal> EquealRMB { get; set; }
        public string Client { get; set; }
        public string ClientType { get; set; }
        public string Bank { get; set; }
        public string CheckNum { get; set; }
        public string PayMode { get; set; }
        public string Reason { get; set; }
        public string DisposeReason { get; set; }
        public Nullable<int> StateFlag { get; set; }
        public Nullable<System.DateTime> recording_time { get; set; }
        public Nullable<int> BillState { get; set; }
        public string SourceReceiptNum { get; set; }
        public string BackReason { get; set; }
        public int IsFromFirst { get; set; }
        public Nullable<int> isShare { get; set; }
        public Nullable<decimal> CashPrize { get; set; }
        public Nullable<decimal> CommisionMoney { get; set; }
        public string areaDirector { get; set; }
        public string PosBank { get; set; }
        public string CompanyNameVAT { get; set; }
        public string TaxPayerVAT { get; set; }
        public string AddressVAT { get; set; }
        public string PhoneVAT { get; set; }
        public string BankVAT { get; set; }
        public string AccountVAT { get; set; }
        public string VATType { get; set; }
        public string eInvoice { get; set; }
        public string TQCode { get; set; }
        public string BUSISH_ID { get; set; }
        public string BUSIAR_ID { get; set; }
        public string BUSISWZ_ID { get; set; }
        public string BUSIWZ_ID { get; set; }
        public string BUSIBA_ID { get; set; }
        public string OtherUsage { get; set; }
        public string DSKHZGUID { get; set; }
    }
}
