//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Flow_Distribution
    {
        public int DistributionId { get; set; }
        public string RootId { get; set; }
        public string WfmId { get; set; }
        public string OrgName { get; set; }
        public string OrgId { get; set; }
        public string UserName { get; set; }
        public string SerialNum { get; set; }
        public string UserId { get; set; }
        public Nullable<decimal> Percent { get; set; }
        public Nullable<decimal> Num { get; set; }
        public Nullable<decimal> Achive { get; set; }
        public Nullable<decimal> Comm { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> StateFlag { get; set; }
        public Nullable<System.DateTime> recording_time { get; set; }
        public string updated_time { get; set; }
        public string AgencyType { get; set; }
        public string AgencyRole { get; set; }
        public Nullable<decimal> CommPercent { get; set; }
        public string UserOrgID { get; set; }
        public string OrgDepartmentID { get; set; }
        public string ParentUserName { get; set; }
        public string ParentSerialNum { get; set; }
        public string ParentOrgName { get; set; }
        public string NewAgencyRole { get; set; }
        public string BUSISH_ID { get; set; }
        public string BUSIAR_ID { get; set; }
        public string BUSISWZ_ID { get; set; }
        public string BUSIWZ_ID { get; set; }
        public string BUSIBA_ID { get; set; }
        public string areaDirector { get; set; }
        public string PercentChange { get; set; }
        public string NumChange { get; set; }
        public string CommChange { get; set; }
        public string AchiveChange { get; set; }
        public string CommPercentChange { get; set; }
        public string AreaName { get; set; }
        public Nullable<int> NotShow { get; set; }
        public string remark { get; set; }
        public Nullable<int> NotNumUser { get; set; }
        public string OrgCode { get; set; }
        public string JobCode { get; set; }
        public string JobName { get; set; }
        public string JobId { get; set; }
    }
}
