//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Flow_Loan
    {
        public string RootId { get; set; }
        public string WfmId { get; set; }
        public string LoanName { get; set; }
        public string PaperType { get; set; }
        public string Paper { get; set; }
        public string LoanType { get; set; }
        public string Reason { get; set; }
        public string ReasonForBank { get; set; }
        public string Bank { get; set; }
        public string Branch { get; set; }
        public string BankLinkMan { get; set; }
        public string BankLinkPhone { get; set; }
        public string Agenct { get; set; }
        public string Telephone { get; set; }
        public Nullable<decimal> InsureMoneyReal { get; set; }
        public Nullable<decimal> InsureDiscount { get; set; }
        public string ContracatType { get; set; }
        public Nullable<decimal> ContractMoney { get; set; }
        public string CommType { get; set; }
        public Nullable<decimal> CommLoan { get; set; }
        public Nullable<decimal> LoanYear { get; set; }
        public Nullable<decimal> LoanRate { get; set; }
        public Nullable<decimal> AccFunLoan { get; set; }
        public Nullable<decimal> AccLoanYear { get; set; }
        public string EvaluateCompany { get; set; }
        public Nullable<decimal> EvaluateMoney { get; set; }
        public string InsureCompany { get; set; }
        public Nullable<decimal> InsureMoney { get; set; }
        public string JudgeCity { get; set; }
        public string JudgeName { get; set; }
        public Nullable<decimal> JudgeMoney { get; set; }
        public string LoanSpecId { get; set; }
        public string LoanSpecName { get; set; }
        public string ChkType { get; set; }
        public string ChkLoanName { get; set; }
        public string ChkBank { get; set; }
        public string ChkBranch { get; set; }
        public Nullable<bool> ChkCorpBank { get; set; }
        public string ChkMoneyType { get; set; }
        public Nullable<decimal> ChkMoney { get; set; }
        public Nullable<decimal> ChkRMB { get; set; }
        public Nullable<decimal> ChkAccLoan { get; set; }
        public string ChkAddress { get; set; }
        public string ChkUserName { get; set; }
        public string ChkDepartment { get; set; }
        public string ChkConclusion { get; set; }
        public string ChkReason { get; set; }
        public string ChkDirectConclusion { get; set; }
        public string ChkDirectReason { get; set; }
        public Nullable<System.DateTime> SendFinanceTime { get; set; }
        public Nullable<System.DateTime> SendLoanSpecTime { get; set; }
        public Nullable<System.DateTime> recording_time { get; set; }
        public Nullable<System.DateTime> updated_time { get; set; }
        public string CQAddress { get; set; }
        public string ChkUserId { get; set; }
        public string FlowName { get; set; }
    }
}
