//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Flow_DistributionCMS
    {
        public int DistributionId { get; set; }
        public string RootId { get; set; }
        public string WfmId { get; set; }
        public string OrgName { get; set; }
        public string OrgId { get; set; }
        public string UserName { get; set; }
        public string SerialNum { get; set; }
        public string UserId { get; set; }
        public Nullable<decimal> Percent { get; set; }
        public Nullable<decimal> Num { get; set; }
        public Nullable<decimal> Achive { get; set; }
        public Nullable<decimal> Comm { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> StateFlag { get; set; }
        public Nullable<System.DateTime> recording_time { get; set; }
        public string updated_time { get; set; }
        public string AgencyType { get; set; }
        public string AgencyRole { get; set; }
        public Nullable<decimal> CommPercent { get; set; }
    }
}
