//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Flow_CaseUnionDetail
    {
        public int CUID { get; set; }
        public string CU_WfmId { get; set; }
        public string WfmId { get; set; }
        public string OldRootId { get; set; }
        public string NewRootId { get; set; }
        public string OldCaseNum { get; set; }
        public string NewCaseNum { get; set; }
        public System.DateTime recording_Time { get; set; }
    
        public virtual T_Flow_CaseUnion T_Flow_CaseUnion { get; set; }
    }
}
