//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Flow_NonIncomeDetail
    {
        public string rootid { get; set; }
        public string wfmid { get; set; }
        public Nullable<decimal> CooprateAmount { get; set; }
        public string CooprateType { get; set; }
        public Nullable<decimal> RealPayout { get; set; }
        public string RealPayoutType { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public string TaxType { get; set; }
        public Nullable<decimal> CooprateAmount1 { get; set; }
        public string CooprateType1 { get; set; }
        public Nullable<decimal> RealPayout1 { get; set; }
        public string RealPayoutType1 { get; set; }
        public Nullable<decimal> Tax1 { get; set; }
        public string TaxType1 { get; set; }
        public string UComP1 { get; set; }
        public string UComName1 { get; set; }
        public string UComPName1 { get; set; }
        public string UComDuty1 { get; set; }
        public string DBPhone1 { get; set; }
        public string SFZCode1 { get; set; }
        public string PayReason1 { get; set; }
        public Nullable<decimal> CooprateAmount2 { get; set; }
        public string CooprateType2 { get; set; }
        public Nullable<decimal> RealPayout2 { get; set; }
        public string RealPayoutType2 { get; set; }
        public Nullable<decimal> Tax2 { get; set; }
        public string TaxType2 { get; set; }
        public string UComP2 { get; set; }
        public string UComName2 { get; set; }
        public string UComPName2 { get; set; }
        public string UComDuty2 { get; set; }
        public string DBPhone2 { get; set; }
        public string SFZCode2 { get; set; }
        public string PayReason2 { get; set; }
        public Nullable<decimal> CooprateAmount3 { get; set; }
        public string CooprateType3 { get; set; }
        public Nullable<decimal> RealPayout3 { get; set; }
        public string RealPayoutType3 { get; set; }
        public decimal Tax3 { get; set; }
        public string TaxType3 { get; set; }
        public string UComP3 { get; set; }
        public string UComName3 { get; set; }
        public string UComPName3 { get; set; }
        public string UComDuty3 { get; set; }
        public string DBPhone3 { get; set; }
        public string SFZCode3 { get; set; }
        public string PayReason3 { get; set; }
        public Nullable<decimal> ZJAmount { get; set; }
        public string ZJType { get; set; }
        public string ZJDX { get; set; }
        public decimal ZJAmount1 { get; set; }
        public string ZJType1 { get; set; }
        public string ZJDX1 { get; set; }
        public decimal ZJAmount2 { get; set; }
        public string ZJType2 { get; set; }
        public string ZJDX2 { get; set; }
        public decimal NonCorpIncome { get; set; }
        public string NonCorpIncomeType { get; set; }
        public Nullable<System.DateTime> RentStartTime { get; set; }
        public Nullable<System.DateTime> RentEndTime { get; set; }
        public System.DateTime dRecordTime { get; set; }
        public string UComCmName1 { get; set; }
        public string UComCmName2 { get; set; }
        public string UComCmName3 { get; set; }
        public string RealPayout1Change { get; set; }
        public string Tax1Change { get; set; }
        public string CooprateAmount1Change { get; set; }
        public string RealPayout2Change { get; set; }
        public string Tax2Change { get; set; }
        public string CooprateAmount2Change { get; set; }
        public string RealPayout3Change { get; set; }
        public string Tax3Change { get; set; }
        public string CooprateAmount3Change { get; set; }
        public string NonCorpIncomeChange { get; set; }
        public string ZJAmount1Change { get; set; }
        public string ZJAmount2Change { get; set; }
    }
}
