//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Flow_GatherPay
    {
        public int GatherPayId { get; set; }
        public string RootId { get; set; }
        public string WfmId { get; set; }
        public string ReceiptNum { get; set; }
        public Nullable<System.DateTime> GPDate { get; set; }
        public string Proposer { get; set; }
        public string ProposerId { get; set; }
        public Nullable<int> GetInOrgId { get; set; }
        public string GetInOrgName { get; set; }
        public Nullable<int> GetOutOrgId { get; set; }
        public string GetOutOrgName { get; set; }
        public string UserName { get; set; }
        public string UserCode { get; set; }
        public string Usage { get; set; }
        public string PrintAddress { get; set; }
        public Nullable<System.DateTime> PrintTime { get; set; }
        public string MoneyType { get; set; }
        public Nullable<decimal> MoneyAmount { get; set; }
        public string Client { get; set; }
        public string ClientType { get; set; }
        public string Bank { get; set; }
        public string BankAccount { get; set; }
        public string CheckNum { get; set; }
        public string PayMode { get; set; }
        public string Reason { get; set; }
        public string BackUpReason { get; set; }
        public string BackUpRelated { get; set; }
        public string MortgagePlace { get; set; }
        public Nullable<int> StateFlag { get; set; }
        public string CtmGuid { get; set; }
        public Nullable<System.DateTime> recording_time { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
        public string SourceReceiptNum { get; set; }
        public string PayGUID { get; set; }
        public string RealPayer { get; set; }
        public string PosBank { get; set; }
        public string BankLocal { get; set; }
        public string BankFullName { get; set; }
        public string IDCardType { get; set; }
        public string IDCard { get; set; }
        public string Content { get; set; }
        public string PayerType { get; set; }
        public string Payer { get; set; }
        public string OtherReason { get; set; }
        public string OtherUsage { get; set; }
        public string GetInOrgIdA { get; set; }
        public string GetOutOrgIdA { get; set; }
    }
}
