//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Flow_CaseOver
    {
        public string RootId { get; set; }
        public string WfmId { get; set; }
        public Nullable<System.DateTime> OwnerChangeDate { get; set; }
        public string DealAnjie { get; set; }
        public Nullable<System.DateTime> HouseGivenDate { get; set; }
        public Nullable<System.DateTime> PaperChangeDate { get; set; }
        public string LoanType { get; set; }
        public Nullable<System.DateTime> LoanDate { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> recording_time { get; set; }
        public Nullable<System.DateTime> updated_time { get; set; }
        public string EndCaseType { get; set; }
        public string YCGH { get; set; }
        public string IsDealAnjie { get; set; }
        public string DealAnjieCode { get; set; }
        public string DealAnjieID { get; set; }
        public string DealAnjieOrgName { get; set; }
        public string DealAnjieOrgID { get; set; }
        public string IsSignAnjie { get; set; }
        public string SignAnjieCode { get; set; }
        public string SignAnjieID { get; set; }
        public string SignAnjieOrgName { get; set; }
        public string SignAnjieOrgID { get; set; }
        public string DealContractDate { get; set; }
        public string SignAnjie { get; set; }
        public string HouseGivenType { get; set; }
    }
}
