//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Flow_CaseUnion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Flow_CaseUnion()
        {
            this.T_Flow_CaseUnionDetail = new HashSet<T_Flow_CaseUnionDetail>();
        }
    
        public string CU_WfmId { get; set; }
        public string UnionRootID { get; set; }
        public string UnionCaseNum { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUserID { get; set; }
        public string UnionAction { get; set; }
        public Nullable<System.DateTime> LawTime { get; set; }
        public string LawUserID { get; set; }
        public Nullable<System.DateTime> FinanceTime { get; set; }
        public string FinanceUserID { get; set; }
        public string FinanceUserName { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public Nullable<System.DateTime> BalanceTime { get; set; }
        public int StateFlag { get; set; }
        public Nullable<System.DateTime> Recording_Time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Flow_CaseUnionDetail> T_Flow_CaseUnionDetail { get; set; }
    }
}
