//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Flow_Mortgage
    {
        public string RootId { get; set; }
        public string WfmId { get; set; }
        public Nullable<System.DateTime> SigningTimeFrom { get; set; }
        public Nullable<System.DateTime> SigningTimeTo { get; set; }
        public string SigningAddress { get; set; }
        public string SignOnScene { get; set; }
        public string ReasonForSignAbsent { get; set; }
        public string IsLoaned { get; set; }
        public string IsPledged { get; set; }
        public Nullable<System.DateTime> DisposeDate { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public string SendOnScene { get; set; }
        public string ReasonForSendAbsent { get; set; }
        public Nullable<decimal> FullMoney { get; set; }
        public string SignOrgId { get; set; }
        public string SignOrgName { get; set; }
        public string SignUserId { get; set; }
        public string SignUserName { get; set; }
        public Nullable<decimal> SignPercent { get; set; }
        public string SendOrgId { get; set; }
        public string SendOrgName { get; set; }
        public string SendUserId { get; set; }
        public string SendUserName { get; set; }
        public Nullable<decimal> SendPercent { get; set; }
        public Nullable<System.DateTime> recording_time { get; set; }
        public string NewProperty { get; set; }
        public string FlowType { get; set; }
    }
}
