//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Flow_Clients
    {
        public string Guid { get; set; }
        public string RootId { get; set; }
        public string WfmId { get; set; }
        public string DisplayName { get; set; }
        public string E_mail { get; set; }
        public string E_mail1 { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string Mobile1 { get; set; }
        public string FAX { get; set; }
        public string Postal_Code_ { get; set; }
        public string Address { get; set; }
        public string PIN_TYPE { get; set; }
        public string PIN_CODE { get; set; }
        public Nullable<int> DS_Type { get; set; }
        public Nullable<System.DateTime> recording_time { get; set; }
        public Nullable<System.DateTime> updated_time { get; set; }
    }
}
