//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Flow_DelayCommission
    {
        public int ID { get; set; }
        public string RootId { get; set; }
        public string WfmId { get; set; }
        public string PComsiCondition1 { get; set; }
        public Nullable<System.DateTime> PComsiDate1 { get; set; }
        public Nullable<decimal> PComsi1 { get; set; }
        public string PComsiRemark1 { get; set; }
        public string PComsiCondition2 { get; set; }
        public Nullable<System.DateTime> PComsiDate2 { get; set; }
        public Nullable<decimal> PComsi2 { get; set; }
        public string PComsiRemark2 { get; set; }
        public string PComsiCondition3 { get; set; }
        public Nullable<System.DateTime> PComsiDate3 { get; set; }
        public Nullable<decimal> PComsi3 { get; set; }
        public string PComsiRemark3 { get; set; }
        public string CComsiCondition1 { get; set; }
        public Nullable<System.DateTime> CComsiDate1 { get; set; }
        public Nullable<decimal> CComsi1 { get; set; }
        public string CComsiRemark1 { get; set; }
        public string CComsiCondition2 { get; set; }
        public Nullable<System.DateTime> CComsiDate2 { get; set; }
        public Nullable<decimal> CComsi2 { get; set; }
        public string CComsiRemark2 { get; set; }
        public string CComsiCondition3 { get; set; }
        public Nullable<System.DateTime> CComsiDate3 { get; set; }
        public Nullable<decimal> CComsi3 { get; set; }
        public string CComsiRemark3 { get; set; }
        public string FlowName { get; set; }
        public string AreaDirector { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
        public Nullable<System.DateTime> dRecordTime { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public Nullable<bool> IsWast { get; set; }
        public Nullable<int> IsLast { get; set; }
    }
}
