//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Flow_LoanChange
    {
        public string RootId { get; set; }
        public string CaseQuHR { get; set; }
        public string CaseLuHR { get; set; }
        public string CaseLongHR { get; set; }
        public string CaseHaoHR { get; set; }
        public string CaseShiHR { get; set; }
        public string LoanCircsR { get; set; }
        public string NoLoanCauseR { get; set; }
        public string LoanBankR { get; set; }
        public string GSbankR { get; set; }
        public string HandleR { get; set; }
        public string HandleJobR { get; set; }
        public string HandlePHR { get; set; }
        public string BankNameR { get; set; }
        public string SubbranchR { get; set; }
        public string PhoneKR { get; set; }
        public string HandleKR { get; set; }
        public string HandleKPHR { get; set; }
        public string AppointR { get; set; }
        public string XunBankR { get; set; }
        public string lCauseR { get; set; }
        public string OtherR { get; set; }
        public string NameBankR { get; set; }
        public string BranchSubR { get; set; }
        public string PhoneKHR { get; set; }
        public string LinkmanR { get; set; }
        public string LinkmanJR { get; set; }
        public string LinkmanPR { get; set; }
        public string LoanNameR { get; set; }
        public string PaperStyleR { get; set; }
        public string PSOtherR { get; set; }
        public string CodeR { get; set; }
        public string AttorneyR { get; set; }
        public string AttNameR { get; set; }
        public string AttPhoneR { get; set; }
        public string InsuranceR { get; set; }
        public string InsuranceAgioR { get; set; }
        public string HTPriceR { get; set; }
        public string CLoanR { get; set; }
        public string CLoanYearR { get; set; }
        public string LoanRateR { get; set; }
        public string ALoanR { get; set; }
        public string ALoanYearR { get; set; }
        public string EvaluationR { get; set; }
        public string EvaluationMR { get; set; }
        public string AssureR { get; set; }
        public string AssureMR { get; set; }
        public string GreffierR { get; set; }
        public string GreffierNR { get; set; }
        public string dChangeCauseR { get; set; }
        public string tChangeCauseR { get; set; }
        public string RecordeUser { get; set; }
        public Nullable<System.DateTime> RecordeTime { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string LoanWfmid { get; set; }
        public Nullable<int> PushState { get; set; }
        public Nullable<System.DateTime> PushTime { get; set; }
        public string FailReason { get; set; }
        public string pushUser { get; set; }
        public string GreffierMR { get; set; }
    }
}
