//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_innerfinance_case
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_innerfinance_case()
        {
            this.t_innerfinance_flow = new HashSet<t_innerfinance_flow>();
        }
    
        public string RootId { get; set; }
        public string CaseType { get; set; }
        public string ReceiptNum { get; set; }
        public Nullable<decimal> Rootbalance { get; set; }
        public Nullable<decimal> HongKongdollar { get; set; }
        public Nullable<decimal> USAdollarbalance { get; set; }
        public Nullable<decimal> Yenbalance { get; set; }
        public string CheckString { get; set; }
        public Nullable<System.DateTime> lastupdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_innerfinance_flow> t_innerfinance_flow { get; set; }
    }
}
