//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_innerfinance_flow
    {
        public int id { get; set; }
        public string RootId { get; set; }
        public string WfmID { get; set; }
        public Nullable<int> statueflag { get; set; }
        public Nullable<System.DateTime> processTime { get; set; }
        public string processUser { get; set; }
    
        public virtual t_innerfinance_case t_innerfinance_case { get; set; }
    }
}
