//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Log_News
    {
        public long id { get; set; }
        public string newsType { get; set; }
        public string newsContent { get; set; }
        public string sender { get; set; }
        public string senderName { get; set; }
        public Nullable<System.DateTime> senderTime { get; set; }
        public string receiver { get; set; }
        public Nullable<System.DateTime> receiverTime { get; set; }
        public int isRead { get; set; }
        public Nullable<System.DateTime> drecordTime { get; set; }
        public string actType { get; set; }
        public string actUrl { get; set; }
        public string newsTitle { get; set; }
        public Nullable<int> orderby { get; set; }
        public string wfmid { get; set; }
        public string rootid { get; set; }
    }
}
