//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Log_CommissionFollow
    {
        public System.Guid Id { get; set; }
        public string RootId { get; set; }
        public string CaseNumber { get; set; }
        public string Flower { get; set; }
        public string Roler { get; set; }
        public Nullable<System.DateTime> FlowDate { get; set; }
        public string FlowContent { get; set; }
        public string FlowStatus { get; set; }
        public Nullable<byte> FlowType { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string Note { get; set; }
        public string HaveDone { get; set; }
        public string WillDo { get; set; }
        public string UserId { get; set; }
        public string UpDown { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public Nullable<System.DateTime> RecordTime { get; set; }
    }
}
