//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Log_PrintCash
    {
        public long LogID { get; set; }
        public string PrintNum { get; set; }
        public string PrintUserID { get; set; }
        public string PrintUserName { get; set; }
        public string PrintOrgID { get; set; }
        public string PrintOrgName { get; set; }
        public Nullable<System.DateTime> PrintTime { get; set; }
        public int IsSucess { get; set; }
        public string PMessage { get; set; }
        public System.DateTime dRecordCreateTime { get; set; }
    }
}
