//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Log_EditClient
    {
        public int id { get; set; }
        public string rootID { get; set; }
        public string UserID { get; set; }
        public string userName { get; set; }
        public string clientType { get; set; }
        public string ChangeDetail { get; set; }
        public string NewContent { get; set; }
        public string OldContent { get; set; }
        public System.DateTime dRecordTime { get; set; }
    }
}
