//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Pro_ProjectUser
    {
        public long ProUserID { get; set; }
        public string ProjectId { get; set; }
        public string DeveloperName { get; set; }
        public string userCode { get; set; }
        public string UserName { get; set; }
        public string userId { get; set; }
        public string ManagerCode { get; set; }
        public string ManagerName { get; set; }
        public string ManagerUserID { get; set; }
        public string UserRole { get; set; }
        public int isNew { get; set; }
        public System.DateTime dRecordTime { get; set; }
        public string ProUser { get; set; }
        public string EmpGuid { get; set; }
        public string EstateUserID { get; set; }
        public string Wfmid { get; set; }
    }
}
