//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Pro_Project
    {
        public string ProjectId { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectNum { get; set; }
        public string PreProjectName { get; set; }
        public string ProjectName { get; set; }
        public string projectAddress { get; set; }
        public string OrgFullName { get; set; }
        public string orgName { get; set; }
        public string orgCode { get; set; }
        public string Developer { get; set; }
        public decimal AnJieCharge { get; set; }
        public int Status { get; set; }
        public int isFirst { get; set; }
        public Nullable<int> OrgType { get; set; }
        public System.DateTime createTime { get; set; }
        public Nullable<System.DateTime> drecordTime { get; set; }
        public string EstateGuid { get; set; }
        public string DailiType { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
    }
}
