//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Pro_ProjectDaili
    {
        public long ProDevID { get; set; }
        public string ProjectId { get; set; }
        public string wfmid { get; set; }
        public Nullable<decimal> StartRate { get; set; }
        public Nullable<decimal> EndRate { get; set; }
        public Nullable<System.DateTime> Starttime { get; set; }
        public Nullable<System.DateTime> Endtime { get; set; }
        public long isNew { get; set; }
        public int IsWast { get; set; }
        public Nullable<System.DateTime> Createtime { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
        public string DailiType { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public System.DateTime dRecordTime { get; set; }
        public string projectInfo { get; set; }
        public string commCondition { get; set; }
        public Nullable<System.DateTime> getLoanTime { get; set; }
        public Nullable<int> isFinalPayment { get; set; }
        public Nullable<decimal> FinalPaymentRate { get; set; }
        public Nullable<int> isCashPrize { get; set; }
        public Nullable<int> ProxyNum { get; set; }
    }
}
