//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Pro_ProjectCashRule
    {
        public int Cid { get; set; }
        public string wfmid { get; set; }
        public string projectId { get; set; }
        public string cashRule { get; set; }
        public Nullable<decimal> cashAmount { get; set; }
        public Nullable<int> iswaste { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public Nullable<System.DateTime> drecordTime { get; set; }
    }
}
