//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_pub_UserParents
    {
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string BranchMgr { get; set; }
        public string SeniorMgr { get; set; }
        public string AreaMgr { get; set; }
        public string AreaMajordomo { get; set; }
        public string VicePresident { get; set; }
        public string branchid { get; set; }
        public string branchname { get; set; }
    }
}
