//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Receipt_Yellow
    {
        public string ReceiptNum { get; set; }
        public string wfmid { get; set; }
        public string PropertyName { get; set; }
        public string OrgName { get; set; }
        public string OrgId { get; set; }
        public string UserName { get; set; }
        public string UserSerial { get; set; }
        public string ReturnState { get; set; }
        public Nullable<int> StateFlag { get; set; }
        public string CheckId { get; set; }
        public string CheckName { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string RootId { get; set; }
        public string OrgIdA { get; set; }
    }
}
