//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Receipt_Detail
    {
        public string Serial { get; set; }
        public Nullable<int> rcptSetId { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string ReturnId { get; set; }
        public string ReturnName { get; set; }
        public Nullable<System.DateTime> ReturnTime { get; set; }
        public string CheckId { get; set; }
        public string CheckName { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
        public Nullable<int> Iswaste { get; set; }
        public string StateFlag { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
    
        public virtual t_Receipt_Manage t_Receipt_Manage { get; set; }
    }
}
