//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Receipt_Log
    {
        public int rcptSetId { get; set; }
        public string SerialBegin { get; set; }
        public string SerialEnd { get; set; }
        public string OwnerId { get; set; }
        public string OwnerName { get; set; }
        public string OwnerSerial { get; set; }
        public string OwnerOrg { get; set; }
        public string OwnerOrgId { get; set; }
        public string AgentId { get; set; }
        public string AgentName { get; set; }
        public string AgentSerial { get; set; }
        public string AgentOrgId { get; set; }
        public string AgentOrg { get; set; }
        public string Remark { get; set; }
        public string StateFlag { get; set; }
        public string Sendid { get; set; }
        public string SendName { get; set; }
        public Nullable<System.DateTime> GivenTime { get; set; }
        public string EditId { get; set; }
        public string EditName { get; set; }
        public Nullable<System.DateTime> EditTime { get; set; }
        public string LogMassage { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string OwnerOrgIdA { get; set; }
    }
}
